### ISSUE TITLE
The system cannot restart because the configuration is not valid: Platform error sensor.cryptostate - Integration 'cryptostate' not found

### ISSUE THREAD

**Issue by t34wrj** [BigNocciolino/CryptoTracker#14]
I am having trouble installing this integration. Having installed it in HACS, and added it to my configuration.yaml, I receive the following error:

'The system cannot restart because the configuration is not valid: Platform error sensor.cryptostate - Integration 'cryptostate' not found'

I have copied and pasted the YAML from the example and this still does not work.

Is this anything to do with the spelling of the 'custom_components/Crypto**Trakcer**'?

Thanks for your help.

**Comment by BigNocciolino** [comment]
Hi thanks for reporting.

First of all, after installing the component, before modifying the `configuration.yaml` file, restart the server and then modify the configuration file.
And after another reboot everything should work.

If that doesn't work it is likely that the
component installation process was unsuccessful. To check, you should check if in the `/config/custom_components` folder if there is a folder called `cryptostate` and if the necessary files are present.

If they are not present, try to delete the component from HACS and retry the installation

**Comment by t34wrj** [comment]
Thanks. I reinstalled this in HACS and there is now no longer a 'custom_components/CryptoTrakcer' folder present...it now shows 'custom_components/cryptostate' instead.

**Comment by BigNocciolino** [comment]
Hi, now technically the component should work, let me know.

**Comment by t34wrj** [comment]
Hi - this works really well now. Thank you.
