### ISSUE TITLE
New beta..

### ISSUE THREAD

**Issue by ranrinc** [BigNocciolino/CryptoTracker#21]
Testing the new beta.. however it seems nothing being grab from the API?

**Comment by BigNocciolino** [comment]
Hi, thanks for testing the beta, is there some logs from the component?

**Comment by GazTheGeek** [comment]
I'm testing Alpha 2.0 3. It wasn't clear to me what to enter in the UI. I put "btc" in the first box (Nothing showing what to put there) "aud" in the second and "btc-aud" in the third. Result is "unknown"

**Comment by BigNocciolino** [comment]
Hello, the box, it has no help because I forgot to update the file for the English translation. (I'm updating it now)

For the rest I did not understand, does the component work or are there problems?

**Comment by GazTheGeek** [comment]
> Hello, the box, it has no help because I forgot to update the file for the English translation. (I'm updating it now)
> 
> For the rest I did not understand, does the component work or are there problems?

Thanks for your work on this. I was using integration many times every day. Sorry if I wasn't clear in my explanation. I am not getting any errors in the logs but the sensor is showing "Unknown". Did I enter the correct information?

**Comment by BigNocciolino** [comment]
I found the problem, now the sensor should work too, because for the tests I had entered a fixed parameter for updating the sensor and I forgot it there -_-. The component should now work. **Sorry**

**Comment by GazTheGeek** [comment]
Do I need to do something. Or wait for the next release? Sorry for my ignorance.

**Comment by BigNocciolino** [comment]
I just created a new release

**Comment by GazTheGeek** [comment]
Got it thanks. Its working as expected. Thanks for your hard work. Really appreciated.

**Comment by BigNocciolino** [comment]
Let me know if the component works ;)

**Comment by GazTheGeek** [comment]
> Let me know if the component works ;)

Yes - Its works great. Thanks. Can I suggest you use the terms "Crypto Ticker" and "Base Ticker" in the UI configuration boxes? Nice work.

**Comment by BigNocciolino** [comment]
Actually it would be better, do you want to create a pull request, or can I update them myself?

**Comment by GazTheGeek** [comment]
I'm sorry I am not a developer. I don't know how to do an update. It's just a suggestion to help less technical people like me. Thanks again for your work getting this fixed.

**Comment by GazTheGeek** [comment]
Some feed back from letting it run over night.

1. I'm getting this error in the logs.
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:471 
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: February 13, 2022, 10:10:10 PM (3 occurrences) 
Last logged: February 13, 2022, 10:50:10 PM

The unit of sensor.btc_aud (None) does not match the unit of already compiled statistics (AUD). Generation of long term statistics will be suppressed unless the unit changes back to AUD. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.eth_aud (None) does not match the unit of already compiled statistics (AUD). Generation of long term statistics will be suppressed unless the unit changes back to AUD. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.ada_aud (None) does not match the unit of already compiled statistics (AUD). Generation of long term statistics will be suppressed unless the unit changes back to AUD. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this


Secondly. I use this data to create a chart. and the chart is not showing any history. Just the current price with a straight horizontal line. Looks like history is not being stored in the database?

**Comment by ranrinc** [comment]
Hi sorry for the late reply, I finally have it up and running, however missing some crypto that I used to monitor. 

SAND, XRP, and FTM 

Hope those 3 will be added soon.

and yes getting the same error like GazTheGeek and yes my graphics did not appear too

**Comment by BigNocciolino** [comment]
Hi, I would like to clarify that with this beta the API has been changed, so consequently the old values ​​generated before cannot be recovered (as they are also unreliable).

> Secondly. I use this data to create a chart. and the chart is not showing any history. Just the current price with a straight horizontal line. Looks like history is not being stored in the database?

As for the graphs, they do not show data because the API updates every day, and the component has a scan interval of 12 hours, so to populate the databases with some data, you have to wait a little.

As far as @GazTheGeek's mistake is concerned, try to watch [here](https://community.home-assistant.io/t/generation-of-long-term-statistics-will-be-suppressed-unless-the-unit-changes-back/334959/14).

> Hi sorry for the late reply, I finally have it up and running, however missing some crypto that I used to monitor.
SAND, XRP, and FTM

Unfortunately, I can't do anything about the missing crypto, it concerns the availability of the API

I hope I was as clear as possible.

**Comment by BigNocciolino** [comment]
Hi I'm closing all the old issues, if there are problems with the new version, please open a new issue
