### ISSUE TITLE
Base Currency not recognised

### ISSUE THREAD

**Issue by boomam** [BigNocciolino/CryptoTracker#24]
Hi,  
I get the error - 
>"Invalid format, for a list of supported currencies see: https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json" 
&nbsp;  

This occurs on both the crypto, and the base in the new GUI, despite both being correct.  
I have tried several combinations of crypto types and bases, to no avail.  
&nbsp;  
Is this a known issue?

**Comment by BigNocciolino** [comment]
~~Yes, since the implementation of the fallback mechanism, I'm pushing the commit this afternoon, now I can not.~~

EDIT: after trying to configure a new device I noticed that it works well, I can see the value that are you trying insert?

**Comment by boomam** [comment]
Several were tried.
Base tried as usd, USD, eur, EUR, gbp, GBP
[Crypto Currency](https://www.cryptonator.com/rates/) was tried as, MYST, myst, 1eco, 1ECO, 

Its worth noting as well, that the error around currency comes up above the box for both entry sections - it probably should be adjusted to only show on the base currency section, so as not to confuse things.

**Comment by BigNocciolino** [comment]
Hi, i noticed that you have linked the cryptonator site, the is no longer using the their API, since the recent problems.
Now the component uses the api provided by [[fawazahmed0](https://github.com/fawazahmed0)](https://github.com/fawazahmed0/currency-api).

**To see the available currencies go [here](https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json).**

> Its worth noting as well, that the error around currency comes up above the box for both entry sections - it probably should be adjusted to only show on the base currency section, so as not to confuse things.

Yes, now the component shows the problems for each the boxes, I'm going to fix this.

**Comment by boomam** [comment]
> Hi, i noticed that you have linked the cryptonator site, the is no longer using the their API, since the recent problems. Now the component uses the api provided by [[fawazahmed0](https://github.com/fawazahmed0)](https://github.com/fawazahmed0/currency-api).
> 
> **To see the available currencies go [here](https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json).**
> 

Hi,
That currency list doesn't list the cryptos to convert from, just country currencies.

If the API call to get the crypto is no longer the one referenced, can you link to the crypto currency list that will work?

Thanks!

**Comment by BigNocciolino** [comment]
Hello, in that link there are also cryptocurrencies, only they are the most common ones, as [fawazahmed0](https://github.com/fawazahmed0/currency-api#readme) points out in the documentation. Unfortunately, there is nothing I can do about it. **Also, write crypto codes lowecase**

**Comment by boomam** [comment]
Tried lower case (shown in example text above).

I searched the list, And he only shows a few common ones, like Bitcoin.

Is there a way to revert the plugin to an older one with greater currency compatibility?
As right now it's not useful unless you are using a few of the big ones, whereas pre-update it worked with a much larger set of crypto currencies.

**Comment by MilitaryNerd** [comment]
Agree with boomam above...I want to track my altcoins and this listly is mostly main coins, so not entirely useful and more of a novelty.

**Comment by BigNocciolino** [comment]
Hi, I talked with the owner of the api about the missing of some coins, he told me that every issue/PR is welcome to add new coins. 

So you simply need to go to the [api page](https://github.com/fawazahmed0/exchange-api/issues/40)
