### ISSUE TITLE
Unable to add additional pairs with new 2.0.0. release

### ISSUE THREAD

**Issue by Bodge-IT** [BigNocciolino/CryptoTracker#25]
Using the new 2.0.0 install and configured my first pair through the interface. SFSG. 
However, there is no configure link on the integration panel, so can't amend existing and when looking to add another instance of the integration, it no longer appears in the list.

**Comment by BigNocciolino** [comment]
Hi, for the moment there is no ability to reconfigure an existing device, if you want to modify it you need to delete and reconfigure the device.

For adding a new instance of the component you need to do the exact same thing you did for configure the first time the component: `Configuration` => `Devices & Services` => `+ Add integration` => `Crypto State` 

This will register a new instance of the component with the new entity.

**Comment by Bodge-IT** [comment]
It's not there in the list of integrations

**Comment by BigNocciolino** [comment]
Mabye try to reinstall the component from the hacs sore, this is really weired

**Comment by Bodge-IT** [comment]
I uninstall the pre 2 version before installing 2.0.0 but I will try that

Edit: OK, needs an additional reboot after configuring the first entry but after that seems to be available OK
