### ISSUE TITLE
Possible to convert in chf

### ISSUE THREAD

**Issue by S1M8N** [BigNocciolino/CryptoTracker#3]
Hello,

First thanks for you integration !

I don't no if it's possible to add the possibility to convert crypto money to CHF ?

**Comment by BigNocciolino** [comment]
Ok, I tested and no currently the API does not allow exchanges with Swiss Francs (CHF), I am very sorry but unfortunately it is a problem with the API and not the integration.

I will create a section in the readme with the fiat currencies with what is possible to make the change. 

Thank you so much for letting me know.

**Comment by S1M8N** [comment]
> Ok, I tested and no currently the API does not allow exchanges with Swiss Francs (CHF), I am very sorry but unfortunately it is a problem with the API and not the integration.
> 
> I will create a section in the readme with the fiat currencies with what is possible to make the change.
> 
> Thank you so much for letting me know.

ok, no solution ?

**Comment by BigNocciolino** [comment]
At the moment no, I don't provide the API. See the fiat list in the readme. :(
