### ISSUE TITLE
need to update API 

### ISSUE THREAD

**Issue by kevincaradant** [BigNocciolino/CryptoTracker#36]
Hi @BigNocciolino 

I received an email about migration of the API, please could you update it because it's broken :(

![image](https://github.com/BigNocciolino/CryptoTracker/assets/6093175/ad7a1b8e-c758-4eb3-bb9b-2e0b4d4e5b5b)

Thank you

**Comment by BigNocciolino** [comment]
Hi, sorry for the late response, yes i have also received the migration email.
I'm currently not using homeassistant anymore, but this should be a very simple change, so as soon i have some free time i will work on it.

**Comment by kevincaradant** [comment]
Hi 

No problemo, Oh you left Home Assistant ? what do you use today ? 

Thank you to take it in charge when you will have free time. I think it will be quick to fix also. I hope so :)

**Comment by BigNocciolino** [comment]
Sorry for the late response, now the issue should be fixed with the 2.1.0 release. Let me know

**Comment by kevincaradant** [comment]
Hi
I didn't have time until now to try it but I will try this week.
Thanks

Edit: finally it was more quick to update it than to write my message haha. It's working.
