### ISSUE TITLE
wrong link in readme?

### ISSUE THREAD

**Issue by TylonHH** [BigNocciolino/CryptoTracker#43]
It seems there is an oudated link in the [read.me](https://github.com/BigNocciolino/CryptoTracker?tab=readme-ov-file#setup)

> To get a full list of available currencies visit this [page](https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json).

Link should point to: [https://cdn.jsdelivr.net/npm/fawazahmed0/currency-api@1/latest/currencies.json](https://cdn.jsdelivr.net/npm/fawazahmed0/currency-api@1/latest/currencies.json) ?!?!

**Comment by BigNocciolino** [comment]
Both #42 and this issue should be solved in the newest release, I'm closing, feel free to reopen if needed
