### ISSUE TITLE
new version can't be updated by HACS

### ISSUE THREAD

**Issue by ChristophCaina** [BigNocciolino/CryptoTracker#6]
Hi,
for some time, I am getting the information that an update for CryptoTracker is available.
HACS does show the update from Version d15ccc4 to v1.0.0 - but when I try to update the integration, nothing happens.

I've also tried to uninstall the Integration... but even then, it is still shown as installed with pending update...

Any Idea, how I could update this integration?
I do see the following information in the HA Logs:

```
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:48
Integration: HACS (documentation, issues)
First occurred: 09:54:02 (2 occurrences)
Last logged: 11:54:02

PepegaBruh/CryptoTracker -
```

it seems, that some version information are wrong in the manifest, etc.
Here's the information for the installed integration compared to the downloaded source:

![grafik](https://user-images.githubusercontent.com/26391061/140053447-e676e0f0-27cc-4904-8a1a-6eec00666c6f.png)

**Comment by BigNocciolino** [comment]
Since the last update I have changed the version, as I have created new releases.

Apparently the conflict is about the versions.

To find out, try to manually delete the folder where the component resides:
`/config/custom_components/cryptostate`

Then from hacs check if it detects the installed component, if you uninstall it and reinstall it, otherwise reinstall it.
If it is not detected normally press on **explore and add repositories** search for and install it from there.

**Comment by ChristophCaina** [comment]
thanks.
after deleting the cryptostate folder and removing the config part I could install both versions.
Then added the configuration again - and now it seems working :)

**Comment by ilmaino1984** [comment]
Good mornig. I've the same problem, after deleting the cryptostate folder and removing the config part.
My problem persist.

![Immagine 2021-11-12 073345](https://user-images.githubusercontent.com/58007629/141421455-0a9eafad-cc33-4c65-8a94-e1348ff86a28.png)
![Immagine 2021-11-12 073408](https://user-images.githubusercontent.com/58007629/141421468-3687c3a0-0816-458e-b78a-30a775c56286.png)

![Immagine 2021-11-12 073439](https://user-images.githubusercontent.com/58007629/141421473-49faf189-3694-4c85-b966-61f0519cfe20.png)
![Immagine 2021-11-12 073502](https://user-images.githubusercontent.com/58007629/141421482-4e6e158e-e88d-487f-9a1e-5d5b739d515d.png)

Any idea how can i solve it?

Thanks in advance

Kind Regards

**Comment by ChristophCaina** [comment]
BigNocciolino already provided a solution for this.
You need to:

1. delete `/config/custom_components/cryptostate`
2. maybe restart HA
3. check in HACS - you should be able to install the integration again
