### ISSUE TITLE
Never installed this.  Can't get rid of it.

### ISSUE THREAD

**Issue by Tovrin** [BigNocciolino/CryptoTracker#8]
I've got this integration appearing in HACS saying it needs to be updated.  I've never installed it.  It's not in my repository.  But it's still telling me I have it.  How do I get rid of this?

**Comment by BigNocciolino** [comment]
Hi, it's a really weird problem.

Try to check in the folder `/config / custom_components` look for a folder with the name `cryptostate` or `cryptotracker`, if you find one, delete it manually by restarting the problem should be solved.

**Comment by Tovrin** [comment]
It is weird.  What makes it weirder is there is no `cryptostate` or `cryptotracker` folders in the `/config/custom_components`.  It still seems to register the plugin with version `d15ccc4`

Not sure what's going on there.

**Comment by imregmelig** [comment]
Thanks! Great to be able to follow this on my [Home Habit based panel](https://community.home-assistant.io/t/home-habit-touch-panel/269513) 😀
Would be nice if you were able to control the currencies from the interface instead. Saves a double restart.

**Comment by el97** [comment]
I'm having the same problem as @Tovrin. I can't see any folders with the name `cryptostate` or `cryptotracker`
