### ISSUE TITLE
Cant find this in HACS?

### ISSUE THREAD

**Issue by Rayeliint** [BigNocciolino/CryptoTracker#9]
Has this been removed or???
Nothing in HAC's when I search for CryptoTracker

**Comment by BigNocciolino** [comment]
Hello,
no, the project has not been abandoned, nor has it been removed from the hacs store.

I am trying to recreate the problem, to try to fix it, in the meantime you may have to press the "explore and download repositories" button and look for them in the repo.

Sorry for the late response.

**Comment by Rayeliint** [comment]
No problem
Tried that and nothing there at all.
